spring.application.name=Library_management

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
#enter you postgres password
spring.datasource.password=rama 

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
